# fly.toml app configuration file generated for discord-summarizer-web on 2025-01-08T15:12:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-summarizer-web'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  VITE_API_URL = 'https://discord-summarizer-api.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
