version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for development
      - ./backend/src:/app/src
      # Mount the database file
      - ./backend/discord_messages.db:/app/discord_messages.db
    environment:
      - DATABASE_URL=sqlite:///discord_messages.db
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    command: uvicorn src.discord_summarizer.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
