services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for development
      - ./backend/src:/app/src
      # Mount the database file
      - ./backend/discord_messages.db:/app/discord_messages.db
    environment:
      - DATABASE_URL=sqlite:///discord_messages.db
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn src.discord_summarizer.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - frontend
      - backend
