# fly.toml app configuration file generated for discord-summarizer-api on 2025-01-08T15:02:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-summarizer-api'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  UV_COMPILE_BYTECODE = '1'
  UV_LINK_MODE = 'copy'

[[mounts]]
  source = 'discord_data'
  destination = '/app/discord_messages.db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
